backend:
  name: github
  repo: project-numina/project-numina-website
  branch: main
  client_id: Ov23liKoirQYJzlCUy7G

# Configuration pour développement local (optionnel)
# local_backend: true

media_folder: "Assets/uploads"
public_folder: "/Assets/uploads"

collections:
  # Collection pour les membres de la communauté
  - name: "communaute"
    label: "Communauté"
    folder: "data/team"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Nom", name: "name", widget: "string"}
      - {label: "Avatar", name: "image", widget: "image", required: false}
      - {label: "URL", name: "url", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "select", multiple: true, options: ["Active Contributor", "Alumni", "Founding Members", "Scientific Advisors"]}

  # Collection pour les cartes projets
  - name: "projets"
    label: "Cartes Projets"
    folder: "data/projects"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    # Configuration spécifique pour les images de projets
    media_folder: "projects_images"
    public_folder: "/projects_images"
    fields:
      - {label: "Titre", name: "title", widget: "string", hint: "50 caractères maximum", pattern: [".{1,50}", "Le titre doit faire entre 1 et 50 caractères"]}
      - {label: "Tags", name: "tags", widget: "select", multiple: true, options: ["models", "datasets", "tools", "research"], hint: "Sélectionnez un ou plusieurs tags"}
      - {label: "Status + Date", name: "status", widget: "string", hint: "Ex: COMING SOON | JULY 2025 ou UPDATED | MAY 2025"}
      - {label: "Description", name: "description", widget: "text", hint: "Description détaillée du projet"}
      - {label: "Visuel", name: "image", widget: "image", required: false, hint: "Image de présentation du projet"}
      - {label: "Mise en avant", name: "highlight", widget: "boolean", default: false, hint: "Cochez pour afficher en carte large"}
      - {label: "Status de publication", name: "published", widget: "select", options: ["published", "draft"], default: "draft", hint: "Déployé = visible sur le site, Brouillon = masqué"}
      - {label: "CTAs", name: "ctas", widget: "list", required: false, max: 2, hint: "Maximum 2 boutons d'action", fields: [
          {label: "Texte", name: "text", widget: "string"},
          {label: "URL", name: "url", widget: "string"},
          {label: "Type", name: "type", widget: "select", options: ["primary", "secondary"], default: "primary", hint: "Primary = bouton principal, Secondary = bouton secondaire"}
        ]}

  # Collection pour les articles de blog
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Statut", name: "status", widget: "select", options: ["publié", "brouillon"], default: "brouillon"}
      - {label: "CTAs", name: "ctas", widget: "list", required: false, fields: [
          {label: "Texte", name: "text", widget: "string"},
          {label: "URL", name: "url", widget: "string"},
          {label: "Type", name: "type", widget: "select", options: ["primary", "secondary"], default: "primary"}
        ]} 
  - name: "photos_community"
    label: "Photos Community"
    folder: "data/photos_community"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text", required: false} 